server:
  port: 8080

spring:
  application:
    name: wonderful-online-shop-backend
  datasource:
    url: jdbc:mysql://localhost:3306/wonderful?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wujiang520

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: []

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

sa-token:
  token-name: Authorization
  token-style: uuid
  is-log: true
  timeout: 2592000

app:
  upload-dir: uploads

wechat:
  miniapp:
    appid: "wxa5a6e72a40532529"
    secret: "c4073fdae487d370927c6865188e229b"
